const labelColors = [
    { "background": "transparent", "text": "inherit", "name": "None" },
    { "background": "#000000", "text": "white", "name": "Black" },
    { "background": "#180d2f", "text": "white", "name": "Deep Blue" },
    { "background": "#353658", "text": "white", "name": "Dark Slate Blue" },
    { "background": "#686b72", "text": "black", "name": "Slate Grey" },
    { "background": "#8b97b6", "text": "black", "name": "Cold Blue" },
    { "background": "#c5cddb", "text": "black", "name": "Light Periwinkle" },
    { "background": "#ffffff", "text": "black", "name": "White" },
    { "background": "#5ee9e9", "text": "black", "name": "Bright Turquoise" },
    { "background": "#2890dc", "text": "black", "name": "Dodger Blue" },
    { "background": "#1831a7", "text": "white", "name": "Royal Blue" },
    { "background": "#053239", "text": "white", "name": "Dark Teal" },
    { "background": "#005f41", "text": "white", "name": "Deep Green" },
    { "background": "#08b23b", "text": "white", "name": "Emerald" },
    { "background": "#47f641", "text": "black", "name": "Neon Green" },
    { "background": "#e8ff75", "text": "black", "name": "Light Lime" },
    { "background": "#fbbe82", "text": "black", "name": "Peach" },
    { "background": "#de9751", "text": "black", "name": "Bronze" },
    { "background": "#b66831", "text": "black", "name": "Light Brown" },
    { "background": "#8a4926", "text": "black", "name": "Medium Brown" },
    // { "background": "#461c14", "text": "white", "name": "Dark Brown" },
    // { "background": "#1e090d", "text": "white", "name": "Very Dark Brown" },
    { "background": "#720d0d", "text": "white", "name": "Burgundy" },
    { "background": "#813704", "text": "white", "name": "Rust" },
    { "background": "#da2424", "text": "white", "name": "Bright Red" },
    { "background": "#ef6e10", "text": "black", "name": "Orange" },
    { "background": "#ecab11", "text": "black", "name": "Golden" },
    { "background": "#ece910", "text": "black", "name": "Lemon" },
    { "background": "#f78d8d", "text": "black", "name": "Soft Pink" },
    { "background": "#f94e6d", "text": "black", "name": "Watermelon" },
    { "background": "#c12458", "text": "white", "name": "Deep Pink" },
    { "background": "#841252", "text": "white", "name": "Plum" },
    { "background": "#3d083b", "text": "white", "name": "Dark Purple" }
];

export default labelColors;